version: "3.9"
services:
  backend:
    container_name: rate-limiter
    volumes:
      - ./backend:/backend
    build:
      context: "backend/"
      dockerfile: Dockerfile
      target: runner
    ports:
      - 3000:3000
  redis:
    container_name: rate-limiter-redis
    image: redislabs/redistimeseries:1.8.3
    ports:
      - "6379:6379"
